apiVersion: apps/v1
kind: Deployment
metadata:
  name: echonet-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echonet-client
  template:
    metadata:
      labels:
        app: echonet-client
    spec:
      containers:
        - name: echonet-client
          image: durbace/echonet-client:latest
          env:
            - name: SERVER_HOST
              value: "echonet-server-service.default.svc.cluster.local"
            - name: SERVER_PORT
              value: "65432"
          livenessProbe:
            tcpSocket:
              port: 65432
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 65432
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
