apiVersion: apps/v1
kind: Deployment
metadata:
  name: echonet-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echonet-server
  template:
    metadata:
      labels:
        app: echonet-server
    spec:
      containers:
      - name: echonet-server
        image: durbace/echonet-server:latest
        ports:
        - containerPort: 65432
