apiVersion: apps/v1
kind: Deployment
metadata:
  name: echonet-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echonet-client
  template:
    metadata:
      labels:
        app: echonet-client
    spec:
      containers:
        - name: echonet-client
          image: durbace/echonet-client:latest
          env:
            - name: SERVER_HOST
              value: "echonet-server-service"
            - name: SERVER_PORT
              value: "65432"
