apiVersion: v1
kind: Service
metadata:
  name: echonet-client-service
spec:
  selector:
    app: echonet-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
