name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run echo server
      run: |
        python echo-server.py &
      continue-on-error: true

    - name: Delay for server to start
      run: sleep 5

    - name: Run echo client
      run: python client.py

    - name: Kill Python processes
      if: always()
      run: killall python3 || echo "No Python processes to kill"
